#!/usr/bin/env node

const { exec } = require('child_process');

// Shift env and node path
process.argv.shift();
process.argv.shift();

console.log(process.argv);

exec('ls', (err, stdout, stderr) => {
  if (err) {
    // node couldn't execute the command
    return;
  }

  // the *entire* stdout and stderr (buffered)
  console.log(`stdout: ${stdout}`);
  console.log(`stderr: ${stderr}`);
});
